trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  BuildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    publishTestResults: true
    arguments: 'src/FluentCloudflare.sln -c $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: 'src/FluentCloudflare.sln -c $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/FluentCloudflare-publish'

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packagesToPack: src/FluentCloudflare/FluentCloudflare.csproj
    configuration: $(BuildConfiguration)
    packDirectory: $(Build.ArtifactStagingDirectory)/Packages

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
  